# Generated by Django 5.0 on 2023-12-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('dataverse', models.CharField(max_length=255)),
                ('repo_id', models.CharField(max_length=255)),
            ],
        ),
    ]
